if ("${VCPKG_ROOT}" STREQUAL "")
    if(NOT "$ENV{VCPKG_ROOT}" STREQUAL "")
        set(VCPKG_ROOT $ENV{VCPKG_ROOT})
    endif()
endif()
if ("${VCPKG_TRIPLET}" STREQUAL "")
    if (NOT "$ENV{VCPKG_TRIPLET}" STREQUAL "")
        set(VCPKG_TRIPLET $ENV{VCPKG_TRIPLET})
    elseif(NOT "${VCPKG_ROOT}" STREQUAL "")
        set(VCPKG_TRIPLET ${VCPKG_ROOT}\\installed\\x64-windows-static)
        set(VCPKG_TRIPLET_BYGUESS 1)
    else()
        string(APPEND _vcpkg_error "The vcpkg triplet can not be found, please specify VCPKG_TRIPLET, ")
        string(APPEND _vcpkg_error "ex: <vcpkg>/installed/x64-windows-static")
        message(FATAL_ERROR ${_vcpkg_error})
    endif()
endif()

# check vcpkg triple pattern
# https://github.com/Microsoft/vcpkg/blob/master/docs/users/triplets.md
string(REGEX MATCH "x86|x64|arm|arm64-.*" TRIPLET_NAME_OK "${VCPKG_TRIPLET}")

if(NOT "${TRIPLET_NAME_OK}" STREQUAL "" AND EXISTS ${VCPKG_TRIPLET})
    if(VCPKG_TRIPLET_BYGUESS)
        string( APPEND _vcpkg_triple_warn "WARNNING : VCPKG_TRIPLET set to ${VCPKG_TRIPLET} by default, ")
        string( APPEND _vcpkg_triple_warn "you might need to change to the suitable triplet for the ")
        string( APPEND _vcpkg_triple_warn "correct depends libraries")
        message(STATUS ${_vcpkg_triple_warn})
    endif()
else()
    message(FATAL_ERROR "vcpkg triple : ${VCPKG_TRIPLET} not correct, please specify correct VCPKG_TRIPLET")
endif()

message(STATUS "vcpkg triplet: ${VCPKG_TRIPLET}")
set(BOOST_ROOT    ${VCPKG_TRIPLET})
if ("${Boost_LIBRARY_DIR_DEBUG}" STREQUAL "") # if using vcpkg, need to specifiy boost debug dir
    set(Boost_LIBRARY_DIR_DEBUG ${VCPKG_TRIPLET}/debug/lib)
    if(NOT EXISTS Boost_LIBRARY_DIR_DEBUG)
        message(WARNING, "Boost_LIBRARY_DIR_DEBUG : ${Boost_LIBRARY_DIR_DEBUG} not exists.")
    endif()
endif()


message(STATUS "Boost_LIBRARIES : ${Boost_LIBRARIES}")
message(STATUS "Boost_UNIT_TEST_FRAMEWORK_LIBRARY : ${Boost_UNIT_TEST_FRAMEWORK_LIBRARY}")
message(STATUS "Boost_UNIT_TEST_FRAMEWORK_LIBRARY_RELEASE : ${Boost_UNIT_TEST_FRAMEWORK_LIBRARY_RELEASE}")
message(STATUS "Boost_UNIT_TEST_FRAMEWORK_LIBRARY_DEBUG : ${Boost_UNIT_TEST_FRAMEWORK_LIBRARY_DEBUG}")

set(OPENSSL_ROOT_DIR ${VCPKG_TRIPLET})
set(LIBEVENT_ROOT_DIR  ${VCPKG_TRIPLET})
set(LIBDB_CXX_DIR  ${VCPKG_TRIPLET})
set(ZeroMQ_DIR ${VCPKG_TRIPLET}/share/zeromq/)