if ("${VCPKG_ROOT}" STREQUAL "")
    if(NOT "$ENV{VCPKG_ROOT}" SEQEQUAL "")
        set(VCPKG_ROOT $ENV{VCPKG_ROOT})
    endif()
endif()
if ("${VCPKG_TRIPLET}" STREQUAL "")
    if (NOT "$ENV{VCPKG_TRIPLET}" STREQUAL "")
        set(VCPKG_TRIPLET $ENV{VCPKG_TRIPLET})
    elseif(NOT "${VCPKG_ROOT}" SEQEQUAL "")
        if(EXIST ${VCPKG_ROOT}/installed/x64-windows-static)
            set(VCPKG_TRIPLET ${VCPKG_ROOT}/installed/x64-windows-static)
            string( APPNED _vcpkg_triple_warn "WARNNING : VCPKG_TRIPLET set to ${VCPKG_TRIPLET} by default, ")
            string( APPEND _vcpkg_triple_warn "you might need to change to the suitable triplet for the ")
            string( APPNED _vcpkg_triple_warn "correct depends libraries")
            message(STATUS _vcpkg_triple_warn)
        endif()
    else()
        message(FATAL_ERROR "vcpkg triplet not found, please specify VCPKG_TRIPLET (such as : C:\\vcpkg\\installed\\x64-windows-static)")
    endif()
endif()

message(STATUS "VCPKG_TRIPLET = ${VCPKG_TRIPLET}")
set(BOOST_ROOT    ${VCPKG_TRIPLET})
set(OPENSSL_ROOT_DIR ${VCPKG_TRIPLET})
set(LIBEVENT_ROOT_DIR  ${VCPKG_TRIPLET})
set(LIBDB_CXX_DIR  ${VCPKG_TRIPLET})
set(ZeroMQ_DIR ${VCPKG_TRIPLET}/share/zeromq/)